<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxpmmze\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxpmmze/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZxpmmze.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZxpmmze\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZxpmmze\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zxpmmze',
    'container.build_id' => '4fd67d6f',
    'container.build_time' => 1522049599,
));
