<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTre10dq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTre10dq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTre10dq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTre10dq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTre10dq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tre10dq',
    'container.build_id' => 'fdc5dd22',
    'container.build_time' => 1523282756,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTre10dq');
