<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWfp6i3i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWfp6i3i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWfp6i3i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWfp6i3i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWfp6i3i\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wfp6i3i',
    'container.build_id' => '815fadc7',
    'container.build_time' => 1523257872,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWfp6i3i');
